### ISSUE TITLE
[Feature] All tracked plays endpoint

### ISSUE THREAD

**Issue by cpiscos** [Ameobea/osutrack-api#2]
It would be useful to have an endpoint for all tracked plays in the output format of the all recorded hiscores endpoint.

**Comment by Ameobea** [comment]
The `/hiscores` endpoint returns all data that osu!track has access to.  The only data that osu!track pulls from the official osu! API are hiscores.

Unlike the osu! website, however, the `/hiscores` endpoint will return scores that have fallen out of a user's top plays; it will return all hiscores that osu!track has ever seen for a user.
