### ISSUE TITLE
Update Endpoint Broken

### ISSUE THREAD

**Issue by cpiscos** [Ameobea/osutrack-api#4]
https://osutrack-api.ameo.dev/update returns "Cannot GET /update" regardless of user/mode settings.

**Comment by Ameobea** [comment]
Hi,

You need to send a `POST` request to that endpoint.  If you are using `curl` on the command line, you can do it like this:

`curl -X POST "https://osutrack-api.ameo.dev/update?user=4093752&mode=0"`

If you're using a programming language like Python, you may need to change the method you're calling from `.get()`. to `.post()` or something like that.
