### ISSUE TITLE
Is there a way to track Total Hits?

### ISSUE THREAD

**Issue by Imaproshaman** [Ameobea/osutrack-api#7]
I don't mean average or anything. I'm just having a hard time finding any way to do that. osu!daily doesn't show it either. Is that even possible to see?

**Comment by Ameobea** [comment]
That data wasn't exposed in the osu! API back when osu!track was first created.  It's available in the new osu! API v2, but osu!track doesn't use this yet.

It's possible that osu!track will have this data in the future, but for now it's not available.

**Comment by Imaproshaman** [comment]
Okay. Thanks for letting me know. I couldn't really find an answer anywhere.
